server.port=8080

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/corporate
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Si NO quieres que Hibernate te cree tablas automáticamente:
spring.jpa.hibernate.ddl-auto=none

# Para inicializar datos con schema.sql/data.sql
spring.sql.init.mode=always
spring.jpa.show-sql=true

# Charset
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'

# Mantener la app corriendo indefinidamente
server.shutdown=immediate
spring.devtools.restart.enabled=false